version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
      - "8081:8080"
    environment:
      - GRPC_PORT=50051
      - PORT=8080
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  product-service:
    build: ./product-service
    ports:
      - "50052:50052"
      - "8082:8080"
    environment:
      - GRPC_PORT=50052
      - PORT=8080
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  order-service:
    build: ./order-service
    ports:
      - "50053:50053"
      - "8083:8080"
    environment:
      - GRPC_PORT=50053
      - PORT=8080
    depends_on:
      - user-service
      - product-service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/app/tests
    depends_on:
      - user-service
      - product-service
      - order-service