version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "50051:50051"

  product-service:
    build: ./product-service
    ports:
      - "50052:50052"

  order-service:
    build: ./order-service
    ports:
      - "50053:50053"
    depends_on:
      - user-service
      - product-service