# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product_service.proto\x12\x0fproduct_service\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"l\n\x12GetProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"&\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"O\n\x16SearchProductsResponse\x12\x35\n\x08products\x18\x01 \x03(\x0b\x32#.product_service.GetProductResponse\">\n\x16UpdateInventoryRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"*\n\x17UpdateInventoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb6\x02\n\x0eProductService\x12W\n\nGetProduct\x12\".product_service.GetProductRequest\x1a#.product_service.GetProductResponse\"\x00\x12\x63\n\x0eSearchProducts\x12&.product_service.SearchProductsRequest\x1a\'.product_service.SearchProductsResponse\"\x00\x12\x66\n\x0fUpdateInventory\x12\'.product_service.UpdateInventoryRequest\x1a(.product_service.UpdateInventoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=42
  _globals['_GETPRODUCTREQUEST']._serialized_end=81
  _globals['_GETPRODUCTRESPONSE']._serialized_start=83
  _globals['_GETPRODUCTRESPONSE']._serialized_end=191
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_start=193
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_end=231
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_start=233
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_end=312
  _globals['_UPDATEINVENTORYREQUEST']._serialized_start=314
  _globals['_UPDATEINVENTORYREQUEST']._serialized_end=376
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_start=378
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_end=420
  _globals['_PRODUCTSERVICE']._serialized_start=423
  _globals['_PRODUCTSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
