# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\rorder_service\"N\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\'\n\x05items\x18\x02 \x03(\x0b\x32\x18.order_service.OrderItem\"1\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\")\n\x15GetOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\":\n\x16GetOrderStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"&\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"&\n\x13\x43\x61ncelOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9f\x02\n\x0cOrderService\x12V\n\x0b\x43reateOrder\x12!.order_service.CreateOrderRequest\x1a\".order_service.CreateOrderResponse\"\x00\x12_\n\x0eGetOrderStatus\x12$.order_service.GetOrderStatusRequest\x1a%.order_service.GetOrderStatusResponse\"\x00\x12V\n\x0b\x43\x61ncelOrder\x12!.order_service.CancelOrderRequest\x1a\".order_service.CancelOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=38
  _globals['_CREATEORDERREQUEST']._serialized_end=116
  _globals['_ORDERITEM']._serialized_start=118
  _globals['_ORDERITEM']._serialized_end=167
  _globals['_CREATEORDERRESPONSE']._serialized_start=169
  _globals['_CREATEORDERRESPONSE']._serialized_end=208
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=210
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=251
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=253
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=311
  _globals['_CANCELORDERREQUEST']._serialized_start=313
  _globals['_CANCELORDERREQUEST']._serialized_end=351
  _globals['_CANCELORDERRESPONSE']._serialized_start=353
  _globals['_CANCELORDERRESPONSE']._serialized_end=391
  _globals['_ORDERSERVICE']._serialized_start=394
  _globals['_ORDERSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
