name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker images
      run: |
        docker build -t user-service ./user-service
        docker build -t product-service ./product-service
        docker build -t order-service ./order-service
    
    - name: Run Docker Compose
      run: docker-compose up -d
    
    - name: Wait for services to start
      run: sleep 100s
    
    - name: Test running services
      run: |
        curl http://localhost:8081 || true
        curl http://localhost:8082 || true
        curl http://localhost:8083 || true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Install Sentry CLI
      run: curl -sL https://sentry.io/get-cli/ | bash

    - name: Create Sentry release
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      run: |
        # Install or update Sentry CLI
        curl -sL https://sentry.io/get-cli/ | bash || true
        
        # Ensure Sentry CLI is in the PATH
        export PATH=$PATH:/usr/local/bin
        
        SENTRY_RELEASE=$(sentry-cli releases propose-version)
        echo "SENTRY_RELEASE=$SENTRY_RELEASE" >> $GITHUB_ENV
        sentry-cli --log-level=debug releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
        sentry-cli --log-level=debug releases set-commits --auto --ignore-missing $SENTRY_RELEASE

    - name: Deploy User Service to Staging
      run: |
        curl -X POST https://api.heroku.com/apps/douso-user-service-staging/builds \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
        -d '{"source_blob":{"url":"https://github.com/KDreynolds/Douso/archive/main.tar.gz", "version": "${{ github.sha }}"}}'

    - name: Deploy Product Service to Staging
      run: |
        curl -X POST https://api.heroku.com/apps/douso-product-service-staging/builds \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
        -d '{"source_blob":{"url":"https://github.com/KDreynolds/Douso/archive/main.tar.gz", "version": "${{ github.sha }}"}}'

    - name: Deploy Order Service to Staging
      run: |
        curl -X POST https://api.heroku.com/apps/douso-order-service-staging/builds \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
        -d '{"source_blob":{"url":"https://github.com/KDreynolds/Douso/archive/main.tar.gz", "version": "${{ github.sha }}"}}'

    - name: Finalize Sentry release
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: HoTMiXer
        SENTRY_PROJECT: douso
      run: |
        sentry-cli --log-level=debug releases finalize $SENTRY_RELEASE
        sentry-cli --log-level=debug releases deploys $SENTRY_RELEASE new -e staging
